GET http://localhost:3000/

###
GET http://localhost:3000/bye

###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username": "chan",
    "password": "zenyang_...."
}

###
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZm9vYmFyIiwiaWF0IjoxNjgxMTExMDM5LCJleHAiOjE2ODExMTQ2Mzl9.7DG8VHZrgFV7WAzju9ZIvBPFeH6NolV_E3t8PQbmZUc

###

POST  http://localhost:3000/register
Content-Type: application/json

{
    "username": "user2",
    "password": "user2@123"
}

###

POST http://localhost:3000/hash
Content-Type: application/json

{
    "username": "chan",
    "password": "zenyang_...."
}

###
POST http://localhost:3000/login/status
Content-Type: application/json

{
    "username": "chan",
    "password": "zenyang_...."
}


