GET http://localhost:3000/

###

POST  http://localhost:3000/
Content-Type: application/json

{
    "username": "user1",
    "password": "user3@76865123"
}

###

POST  http://localhost:3000/register
Content-Type: application/json

{
    "name": "user3",
    "password": "user3@76865123"

}
