GET http://localhost:3000/

###
GET http://localhost:3000/bye

###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username": "chan",
    "password": "zenyang_...."
}

###
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZm9vYmFyIiwiaWF0IjoxNjgxMTEwMDA4LCJleHAiOjE2ODExMTM2MDh9.2uuWwlJlbW60mwUR1S-synesg23mJ52c_0d5uwviq5A

###

POST  http://localhost:3000/register
Content-Type: application/json

{
    "username": "user2",
    "password": "user2@123"
}

###

POST http://localhost:3000/hash
Content-Type: application/json

{
    "username": "thor",
    "password": "Th....",
    "name": "Thor",
    "email": "thor@utem.edu.my",
    "phone": "011-85496211"
}

###
POST http://localhost:3000/compare
Content-Type: application/json

{
    "username": "chan",
    "password": "zenyang_...."
}


