POST http://localhost:3000/login 
Content-Type: application/json 
 
{ 
    "username": "bob", 
    "password": "ILikeToFixIt" 
} 
 
### 
 
GET http://localhost:3000/hello 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsInBhc3N3b3JkIjoiSUxpa2VUb0ZpeEl0IiwibmFtZSI6IkJvYlRoZUJ1aWxkZXIiLCJlbWFpbCI6ImJvYkBmaXhpdC5jb20iLCJpYXQiOjE2ODExNzI1ODksImV4cCI6MTY4MTE3NjE4OX0.j7BADVQY9AV_LAN6qKZ5Db5xnaSFDkzUFJW-kfGv7es
### 
 
GET http://localhost:3000/